In [4]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('World_Bank_Expenditures_by_Organizational_Unit.csv')

In [3]:
df

,Organizational Unit,Vice Presidential Unit or Grouping,Fiscal Year,"Actuals (US$, Millions)","Subtotals (US$, Millions)",Notes
0,Governance services,Governance services,2009,171.2,NaN,Governance services includes units such as: th...
1,Operational units,Operational units Total,2009,NaN,1317.7,NaN
2,Institutional services,Institutional services,2009,431.8,NaN,Institutional Services includes units such as:...
3,Centrally-managed accounts and programs,Centrally-managed accounts and programs,2009,24.1,NaN,Centrally-managed accounts and programs includ...
4,Administrative services,Administrative services,2009,313.2,NaN,Administrative services Includes General Servi...
...,...,...,...,...,...,...
116,"Reimbursements, fees, others","Reimbursements, fees, others",2019,-574.2,NaN,NaN
117,Centrally-managed accounts and programs,Centrally-managed accounts and programs,2019,80.4,NaN,Centrally-managed accounts and programs includ...
118,Governance services,Governance services,2019,215.5,NaN,Governance services includes units such as: th...
119,Operational units,Global Practices and Cross-Cutting Solutions A...,2019,1292.8,NaN,NaN
120,Total administrative budget,Total administrative budget,2019,NaN,2602.5,NaN

Below we will see a table summarizing the overall expenditures per Organizational Unit.

In [10]:
pivot_table_1 = pd.pivot_table(df, values = 'Actuals (US$, Millions)', index = ['Organizational Unit'],
                               aggfunc = np.sum, fill_value = 0)

In [8]:
pivot_table_1

                                         Actuals (US$, Millions)
Organizational Unit
Administrative services                                   5057.1
Centrally-managed accounts and programs                   2220.9
Governance services                                       2112.8
Grant-making Facilities                                   1258.1
Institutional services                                    4944.0
Operational units                                         7600.4
Reimbursements, fees, others                             -4877.7
Total administrative budget                                  0.0
Total gross administrative budget                            0.0

On the next table, we try to see the Actuals data per year.

In [11]:
pivot_table_2 = pd.pivot_table(df, values = 'Actuals (US$, Millions)', index = ['Organizational Unit'],
                               columns = ['Fiscal Year'],aggfunc = np.sum, fill_value = 0)

In [12]:
pivot_table_2

Fiscal Year,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
Organizational Unit,,,,,,,,,,,
Administrative services,313.2,317.3,335.2,414.5,414.0,467.8,533.5,536.1,542.9,587.1,595.5
Centrally-managed accounts and programs,24.1,136.5,159.2,126.8,289.8,300.6,330.8,353.2,344.4,75.1,80.4
Governance services,171.2,182.4,186.6,190.7,194.4,190.1,181.6,190.7,194.9,214.7,215.5
Grant-making Facilities,199.7,170.1,149.4,135.9,153.1,159.8,109.2,66.4,44.6,35.0,34.9
Institutional services,431.8,439.3,432.7,435.2,421.4,435.9,454.4,451.1,433.3,503.1,505.8
Operational units,0.0,0.0,0.0,0.0,0.0,0.0,1423.1,1364.6,1419.0,1649.1,1744.6
"Reimbursements, fees, others",-309.0,-331.1,-345.0,-377.8,-430.1,-489.3,-507.2,-492.9,-484.9,-536.2,-574.2
Total administrative budget,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Total gross administrative budget,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0